image: node:14

pipelines:
  # default:
  #   - parallel:
  #       - step:
  #           name: Build and Test
  #           caches:
  #             - node
  #           script:
  #             - npm install
  #             - npm test
  #       - step:
  #           name: Lint the node package
  #           script:
  #             - npm install eslint
  #             - npx eslint src
  #           caches:
  #             - node
  branches:
    master:
      - parallel:
          - step:
              name: Build and Test
              caches:
                - node
              script:
                - npm ci
                - npm run build
              artifacts:
                - build/**
          - step:
              name: Security Scan
              script:
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          clone:
            enabled: false
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET_PROD
                LOCAL_PATH: "build"

    dev:
      - parallel:
          - step:
              name: Build and Test
              caches:
                - node
              script:
                - npm ci
                - npm run build
              artifacts:
                - build/**
          - step:
              name: Security Scan
              script:
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Test
          deployment: test
          clone:
            enabled: false
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET_DEV
                LOCAL_PATH: "build"
